# Generated by Django 4.0.5 on 2022-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='delete_comment',
            field=models.CharField(default='Item Deleted', max_length=254),
        ),
        migrations.AddField(
            model_name='inventory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
