# Generated by Django 4.0.5 on 2022-06-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_inventory_options_inventory_delete_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='delete_comment',
            field=models.CharField(default='', max_length=254),
        ),
    ]
